---
- name: Running Emacs ansible playbook...
  hosts: localhost
  tasks:
    - name: Get repo base path
      command: git rev-parse --show-toplevel
      register: repo_base_path

    - set_fact:
        base_path: '{{repo_base_path.stdout}}/'

    - name: Symlink .emacs config to user home directory
      file:
        src: '{{base_path}}.emacs'
        dest: '~/.emacs'
        state: link
        force: yes  # See: https://github.com/ansible/ansible/issues/7627

    - name: Symlink config.org config to user home directory
      file:
        src: '{{base_path}}config.org'
        dest: '~/config.org'
        state: link
        force: yes  # See: https://github.com/ansible/ansible/issues/7627

    - name: Update pacman cache
      # http://docs.ansible.com/ansible/become.html
      become: true
      become_method: sudo  # requires running with --ask-become-pass.
      # https://docs.ansible.com/ansible/pacman_module.html
      pacman:
        update_cache: yes
        # TEMP: commenting out since I should be doing this outside of this
        # playbook as common behaviour.
        #
        # upgrade: yes

    - name: Install Emacs Git package
      aur:
        use: yay
        name:
          - emacs-git


    - name: Enable emacs service
      # https://docs.ansible.com/ansible/latest/modules/systemd_module.html
      # https://wiki.archlinux.org/title/Emacs#As_a_systemd_unit
      systemd:
        name: emacs.service
        enabled: True
        state: started
        scope: user
